"""
Configuration constants for Philadelphia Crime Incidents EDA.

Defines paths, plot settings, and analysis parameters.
"""

from pathlib import Path

# =============================================================================
# PATHS
# =============================================================================

# Project root
PROJECT_ROOT = Path(__file__).parent.parent

# Data paths
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

# Main dataset
CRIME_DATA_PATH = DATA_DIR / "crime_incidents_combined.parquet"

CLEANED_DATA_PATH = PROCESSED_DATA_DIR / "crime_incidents_cleaned.parquet"

# Output paths
ANALYSIS_DIR = PROJECT_ROOT / "analysis"
REPORTS_DIR = PROJECT_ROOT / "reports"
TEMP_DIR = PROJECT_ROOT / ".temp"

# =============================================================================
# DATASET INFO
# =============================================================================

DATASET_INFO = {
    "total_records": 3_496_353,
    "temporal_range": ("2006-01-01", "2026-01-20"),
    "crime_types": 32,
    "police_districts": 26,
}

# =============================================================================
# PLOT SETTINGS
# =============================================================================#

# Figure sizes (in inches)
FIGURE_SIZES = {
    "small": (8, 6),
    "medium": (12, 8),
    "wide": (16, 8),
    "large": (14, 10),
    "heatmap": (16, 12),
    "square": (10, 10),
}

# Color schemes
COLORS = {
    "primary": "#1f77b4",
    "secondary": "#ff7f0e",
    "danger": "#d62728",
    "success": "#2ca02c",
    "warning": "#ffbb00",
    "palette": "tab20",  # matplotlib colormap for categorical data
    "sequential": "YlOrRd",  # for heatmaps
    "diverging": "RdBu_r",  # for diverging data
}

# Philadelphia approximate bounding box
PHILADELPHIA_BBOX = {
    "lon_min": -75.28,
    "lon_max": -74.95,
    "lat_min": 39.86,
    "lat_max": 40.14,
}

# =============================================================================
# ANALYSIS PARAMETERS
# =============================================================================

# Coordinate validation
LON_MIN, LON_MAX = PHILADELPHIA_BBOX["lon_min"], PHILADELPHIA_BBOX["lon_max"]
LAT_MIN, LAT_MAX = PHILADELPHIA_BBOX["lat_min"], PHILADELPHIA_BBOX["lat_max"]

# Date parsing
DATE_COLUMNS = ["dispatch_date", "dispatch_time"]
DATETIME_COLUMN = "dispatch_datetime"

# Missing data threshold for exclusion
MISSING_THRESHOLD = 0.5  # Drop columns with >50% missing

# =============================================================================
# REPORT SETTINGS
# =============================================================================#

REPORT_TITLE = "# Philadelphia Crime Incidents - Exploratory Data Analysis Report"
REPORT_AUTHOR = "Generated by Claude Code"
REPORT_DATE_FORMAT = "%B %d, %Y"

# Markdown section headers
SECTION_HEADERS = {
    "data_quality": "## Phase 1: Data Quality Assessment",
    "temporal": "## Phase 2: Temporal Analysis",
    "categorical": "## Phase 3: Categorical Analysis",
    "spatial": "## Phase 4: Spatial Analysis",
    "cross": "## Phase 5: Cross-Dimensional Analysis",
    "summary": "## Phase 6: Summary and Key Findings",
}

# =============================================================================
# CLUSTERING / RED ZONES ANALYSIS
# =============================================================================#

# Philadelphia center point for map initialization
PHILADELPHIA_CENTER = {"lat": 39.9526, "lon": -75.1652}

# DBSCAN parameters for hotspot detection
# eps_meters: radius for clustering (150m ~ 500ft, patrol-relevant scale)
# min_samples: minimum incidents to form a hotspot
DBSCAN_CONFIG = {
    "eps_meters": 150,  # ~500ft radius for clustering
    "min_samples": 50,  # Minimum incidents for a hotspot
}

# Sampling for performance (full dataset too large for clustering)
CLUSTERING_SAMPLE_SIZE = 500_000  # Sample size for overall hotspot detection

# Crime type groupings for focused hotspot analysis
CRIME_TYPE_FOCUS = {
    "narcotics": ["Narcotics", "Drug Violations"],
    "violent": [
        "Homicide - Criminal",
        "Homicide - Gross Negligence",
        "Rape",
        "Robbery Firearm",
        "Robbery No Firearm",
        "Aggravated Assault Firearm",
        "Aggravated Assault No Firearm",
    ],
    "property": [
        "Burglary Residential",
        "Burglary Non-Residential",
        "Thefts",
        "Theft from Vehicle",
        "Motor Vehicle Theft",
    ],
}

# Hotspot ranking criteria weights
HOTSPOT_WEIGHTS = {
    "incident_count": 0.5,    # 50% weight on total incidents
    "density": 0.3,            # 30% weight on incidents per square km
    "consistency": 0.2,        # 20% weight on year-over-year consistency
}
